# From the terraform output, copy the IP address of the server you want to deploy to
# And then put this in the hosts inventory file:
[servers]

server1 ansible_host=3.250.154.208
server2 ansible_host=34.254.178.173

[servers:vars]
ansible_user=admin
ansible_ssh_private_key_file=/home/runner/.ssh/ansible
ansible_python_interpreter=/usr/bin/python3 

