apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8080;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }
    }
  index.html: |
    <H1>Hello from DevOpsDean Channel!</H1>
    <H1>All DevOps solutions are available!</H1>
    <h2>Please subscribe to my channel!</h2>
